//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kyrsovaya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Билет.
    /// </summary>
    // *** Start programmer edit section *** (Билет CustomAttributes)

    // *** End programmer edit section *** (Билет CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("БилетE", new string[0])]
    [View("БилетL", new string[0])]
    public class Билет : ICSSoft.STORMNET.DataObject
    {
        
        // *** Start programmer edit section *** (Билет CustomMembers)

        // *** End programmer edit section *** (Билет CustomMembers)

        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "БилетE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View БилетE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("БилетE", typeof(IIS.Kyrsovaya.Билет));
                }
            }
            
            /// <summary>
            /// "БилетL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View БилетL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("БилетL", typeof(IIS.Kyrsovaya.Билет));
                }
            }
        }
    }
}
