//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kyrsovaya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Билеты.
    /// </summary>
    // *** Start programmer edit section *** (Билеты CustomAttributes)

    // *** End programmer edit section *** (Билеты CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("БилетыE", new string[] {
            "ДатаПокупки as \'Дата покупки\'",
            "ВремяПокупки as \'Время покупки\'",
            "ДатаПоездки as \'Дата поездки\'",
            "ПунктОтпр as \'Пункт отправления\'",
            "ПунктНазнач as \'Пункт назначения\'",
            "Перевозчик.Наименование as \'Наименование\'",
            "Место as \'Место\'",
            "Клиент_ as \'Покупатель\'",
            "Клиент_.ФИО as \'ФИО покупателя\'",
            "Клиент_.БанкСчет as \'Банковский счет\'",
            "БилетКасса as \'Билет касса\'",
            "БилетКасса.Наименование as \'Место расчета\'",
            "Перевозчик as \'Перевозчик\'"}, Hidden=new string[] {
            "Перевозчик.Наименование",
            "Клиент_.БанкСчет",
            "БилетКасса.Наименование"})]
    [MasterViewDefineAttribute("БилетыE", "Клиент_", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "БанкСчет")]
    [MasterViewDefineAttribute("БилетыE", "БилетКасса", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("БилетыE", "Перевозчик", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("БилетыL", new string[] {
            "ПунктОтпр as \'Пункт отпр\'",
            "ДатаПоездки as \'Дата поездки\'",
            "ДатаПокупки as \'Дата покупки\'",
            "Место as \'Место\'",
            "ПунктНазнач as \'Пункт назнач\'",
            "ВремяПокупки as \'Время покупки\'",
            "Клиент_.БанкСчет as \'Банк счет\'",
            "БилетКасса.Наименование as \'Наименование\'",
            "Перевозчик.Наименование as \'Наименование\'",
            "Клиент_.ФИО"})]
    public class Билеты : ICSSoft.STORMNET.DataObject
    {
        
        private string fПунктОтпр;
        
        private System.DateTime fДатаПоездки;
        
        private System.DateTime fДатаПокупки = System.DateTime.Now;
        
        private int fМесто;
        
        private string fПунктНазнач;
        
        private string fВремяПокупки;
        
        private IIS.Kyrsovaya.Клиент_ fКлиент_;
        
        private IIS.Kyrsovaya.БилетКасса fБилетКасса;
        
        private IIS.Kyrsovaya.Перевозчик fПеревозчик;
        
        // *** Start programmer edit section *** (Билеты CustomMembers)

        // *** End programmer edit section *** (Билеты CustomMembers)

        
        /// <summary>
        /// ВремяПокупки.
        /// </summary>
        // *** Start programmer edit section *** (Билеты.ВремяПокупки CustomAttributes)

        // *** End programmer edit section *** (Билеты.ВремяПокупки CustomAttributes)
        [StrLen(255)]
        public virtual string ВремяПокупки
        {
            get
            {
                // *** Start programmer edit section *** (Билеты.ВремяПокупки Get start)

                // *** End programmer edit section *** (Билеты.ВремяПокупки Get start)
                string result = this.fВремяПокупки;
                // *** Start programmer edit section *** (Билеты.ВремяПокупки Get end)

                // *** End programmer edit section *** (Билеты.ВремяПокупки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Билеты.ВремяПокупки Set start)

                // *** End programmer edit section *** (Билеты.ВремяПокупки Set start)
                this.fВремяПокупки = value;
                // *** Start programmer edit section *** (Билеты.ВремяПокупки Set end)

                // *** End programmer edit section *** (Билеты.ВремяПокупки Set end)
            }
        }
        
        /// <summary>
        /// ДатаПоездки.
        /// </summary>
        // *** Start programmer edit section *** (Билеты.ДатаПоездки CustomAttributes)

        // *** End programmer edit section *** (Билеты.ДатаПоездки CustomAttributes)
        public virtual System.DateTime ДатаПоездки
        {
            get
            {
                // *** Start programmer edit section *** (Билеты.ДатаПоездки Get start)

                // *** End programmer edit section *** (Билеты.ДатаПоездки Get start)
                System.DateTime result = this.fДатаПоездки;
                // *** Start programmer edit section *** (Билеты.ДатаПоездки Get end)

                // *** End programmer edit section *** (Билеты.ДатаПоездки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Билеты.ДатаПоездки Set start)

                // *** End programmer edit section *** (Билеты.ДатаПоездки Set start)
                this.fДатаПоездки = value;
                // *** Start programmer edit section *** (Билеты.ДатаПоездки Set end)

                // *** End programmer edit section *** (Билеты.ДатаПоездки Set end)
            }
        }
        
        /// <summary>
        /// ДатаПокупки.
        /// </summary>
        // *** Start programmer edit section *** (Билеты.ДатаПокупки CustomAttributes)

        // *** End programmer edit section *** (Билеты.ДатаПокупки CustomAttributes)
        public virtual System.DateTime ДатаПокупки
        {
            get
            {
                // *** Start programmer edit section *** (Билеты.ДатаПокупки Get start)

                // *** End programmer edit section *** (Билеты.ДатаПокупки Get start)
                System.DateTime result = this.fДатаПокупки;
                // *** Start programmer edit section *** (Билеты.ДатаПокупки Get end)

                // *** End programmer edit section *** (Билеты.ДатаПокупки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Билеты.ДатаПокупки Set start)

                // *** End programmer edit section *** (Билеты.ДатаПокупки Set start)
                this.fДатаПокупки = value;
                // *** Start programmer edit section *** (Билеты.ДатаПокупки Set end)

                // *** End programmer edit section *** (Билеты.ДатаПокупки Set end)
            }
        }
        
        /// <summary>
        /// Место.
        /// </summary>
        // *** Start programmer edit section *** (Билеты.Место CustomAttributes)

        // *** End programmer edit section *** (Билеты.Место CustomAttributes)
        public virtual int Место
        {
            get
            {
                // *** Start programmer edit section *** (Билеты.Место Get start)

                // *** End programmer edit section *** (Билеты.Место Get start)
                int result = this.fМесто;
                // *** Start programmer edit section *** (Билеты.Место Get end)

                // *** End programmer edit section *** (Билеты.Место Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Билеты.Место Set start)

                // *** End programmer edit section *** (Билеты.Место Set start)
                this.fМесто = value;
                // *** Start programmer edit section *** (Билеты.Место Set end)

                // *** End programmer edit section *** (Билеты.Место Set end)
            }
        }
        
        /// <summary>
        /// ПунктНазнач.
        /// </summary>
        // *** Start programmer edit section *** (Билеты.ПунктНазнач CustomAttributes)

        // *** End programmer edit section *** (Билеты.ПунктНазнач CustomAttributes)
        [StrLen(255)]
        public virtual string ПунктНазнач
        {
            get
            {
                // *** Start programmer edit section *** (Билеты.ПунктНазнач Get start)

                // *** End programmer edit section *** (Билеты.ПунктНазнач Get start)
                string result = this.fПунктНазнач;
                // *** Start programmer edit section *** (Билеты.ПунктНазнач Get end)

                // *** End programmer edit section *** (Билеты.ПунктНазнач Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Билеты.ПунктНазнач Set start)

                // *** End programmer edit section *** (Билеты.ПунктНазнач Set start)
                this.fПунктНазнач = value;
                // *** Start programmer edit section *** (Билеты.ПунктНазнач Set end)

                // *** End programmer edit section *** (Билеты.ПунктНазнач Set end)
            }
        }
        
        /// <summary>
        /// ПунктОтпр.
        /// </summary>
        // *** Start programmer edit section *** (Билеты.ПунктОтпр CustomAttributes)

        // *** End programmer edit section *** (Билеты.ПунктОтпр CustomAttributes)
        [StrLen(255)]
        public virtual string ПунктОтпр
        {
            get
            {
                // *** Start programmer edit section *** (Билеты.ПунктОтпр Get start)

                // *** End programmer edit section *** (Билеты.ПунктОтпр Get start)
                string result = this.fПунктОтпр;
                // *** Start programmer edit section *** (Билеты.ПунктОтпр Get end)

                // *** End programmer edit section *** (Билеты.ПунктОтпр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Билеты.ПунктОтпр Set start)

                // *** End programmer edit section *** (Билеты.ПунктОтпр Set start)
                this.fПунктОтпр = value;
                // *** Start programmer edit section *** (Билеты.ПунктОтпр Set end)

                // *** End programmer edit section *** (Билеты.ПунктОтпр Set end)
            }
        }
        
        /// <summary>
        /// Билеты.
        /// </summary>
        // *** Start programmer edit section *** (Билеты.БилетКасса CustomAttributes)

        // *** End programmer edit section *** (Билеты.БилетКасса CustomAttributes)
        [PropertyStorage(new string[] {
                "БилетКасса"})]
        [NotNull()]
        public virtual IIS.Kyrsovaya.БилетКасса БилетКасса
        {
            get
            {
                // *** Start programmer edit section *** (Билеты.БилетКасса Get start)

                // *** End programmer edit section *** (Билеты.БилетКасса Get start)
                IIS.Kyrsovaya.БилетКасса result = this.fБилетКасса;
                // *** Start programmer edit section *** (Билеты.БилетКасса Get end)

                // *** End programmer edit section *** (Билеты.БилетКасса Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Билеты.БилетКасса Set start)

                // *** End programmer edit section *** (Билеты.БилетКасса Set start)
                this.fБилетКасса = value;
                // *** Start programmer edit section *** (Билеты.БилетКасса Set end)

                // *** End programmer edit section *** (Билеты.БилетКасса Set end)
            }
        }
        
        /// <summary>
        /// Билеты.
        /// </summary>
        // *** Start programmer edit section *** (Билеты.Клиент_ CustomAttributes)

        // *** End programmer edit section *** (Билеты.Клиент_ CustomAttributes)
        [PropertyStorage(new string[] {
                "Клиент_"})]
        [NotNull()]
        public virtual IIS.Kyrsovaya.Клиент_ Клиент_
        {
            get
            {
                // *** Start programmer edit section *** (Билеты.Клиент_ Get start)

                // *** End programmer edit section *** (Билеты.Клиент_ Get start)
                IIS.Kyrsovaya.Клиент_ result = this.fКлиент_;
                // *** Start programmer edit section *** (Билеты.Клиент_ Get end)

                // *** End programmer edit section *** (Билеты.Клиент_ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Билеты.Клиент_ Set start)

                // *** End programmer edit section *** (Билеты.Клиент_ Set start)
                this.fКлиент_ = value;
                // *** Start programmer edit section *** (Билеты.Клиент_ Set end)

                // *** End programmer edit section *** (Билеты.Клиент_ Set end)
            }
        }
        
        /// <summary>
        /// Билеты.
        /// </summary>
        // *** Start programmer edit section *** (Билеты.Перевозчик CustomAttributes)

        // *** End programmer edit section *** (Билеты.Перевозчик CustomAttributes)
        [PropertyStorage(new string[] {
                "Перевозчик"})]
        [NotNull()]
        public virtual IIS.Kyrsovaya.Перевозчик Перевозчик
        {
            get
            {
                // *** Start programmer edit section *** (Билеты.Перевозчик Get start)

                // *** End programmer edit section *** (Билеты.Перевозчик Get start)
                IIS.Kyrsovaya.Перевозчик result = this.fПеревозчик;
                // *** Start programmer edit section *** (Билеты.Перевозчик Get end)

                // *** End programmer edit section *** (Билеты.Перевозчик Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Билеты.Перевозчик Set start)

                // *** End programmer edit section *** (Билеты.Перевозчик Set start)
                this.fПеревозчик = value;
                // *** Start programmer edit section *** (Билеты.Перевозчик Set end)

                // *** End programmer edit section *** (Билеты.Перевозчик Set end)
            }
        }
        
        // *** Start programmer edit section *** (Билеты.Печать CustomAttributes)

        // *** End programmer edit section *** (Билеты.Печать CustomAttributes)
        [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
        public virtual void Печать()
        {
            // *** Start programmer edit section *** (Билеты.Печать method implementation)

            return;
            // *** End programmer edit section *** (Билеты.Печать method implementation)
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "БилетыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View БилетыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("БилетыE", typeof(IIS.Kyrsovaya.Билеты));
                }
            }
            
            /// <summary>
            /// "БилетыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View БилетыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("БилетыL", typeof(IIS.Kyrsovaya.Билеты));
                }
            }
        }
    }
}
