//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kyrsovaya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Клиент_.
    /// </summary>
    // *** Start programmer edit section *** (Клиент_ CustomAttributes)

    // *** End programmer edit section *** (Клиент_ CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("Клиент_E", new string[] {
            "ID as \'ID\'",
            "БанкСчет as \'Банк счет\'",
            "ФИО as \'ФИО\'"})]
    [View("Клиент_L", new string[] {
            "ID as \'ID\'",
            "БанкСчет as \'Банк счет\'",
            "ФИО as \'ФИО\'"})]
    public class Клиент_ : ICSSoft.STORMNET.DataObject
    {
        
        private int fID;
        
        private string fБанкСчет;
        
        private string fФИО;
        
        // *** Start programmer edit section *** (Клиент_ CustomMembers)

        // *** End programmer edit section *** (Клиент_ CustomMembers)

        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (Клиент_.ID CustomAttributes)

        // *** End programmer edit section *** (Клиент_.ID CustomAttributes)
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (Клиент_.ID Get start)

                // *** End programmer edit section *** (Клиент_.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (Клиент_.ID Get end)

                // *** End programmer edit section *** (Клиент_.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент_.ID Set start)

                // *** End programmer edit section *** (Клиент_.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (Клиент_.ID Set end)

                // *** End programmer edit section *** (Клиент_.ID Set end)
            }
        }
        
        /// <summary>
        /// БанкСчет.
        /// </summary>
        // *** Start programmer edit section *** (Клиент_.БанкСчет CustomAttributes)

        // *** End programmer edit section *** (Клиент_.БанкСчет CustomAttributes)
        [StrLen(255)]
        public virtual string БанкСчет
        {
            get
            {
                // *** Start programmer edit section *** (Клиент_.БанкСчет Get start)

                // *** End programmer edit section *** (Клиент_.БанкСчет Get start)
                string result = this.fБанкСчет;
                // *** Start programmer edit section *** (Клиент_.БанкСчет Get end)

                // *** End programmer edit section *** (Клиент_.БанкСчет Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент_.БанкСчет Set start)

                // *** End programmer edit section *** (Клиент_.БанкСчет Set start)
                this.fБанкСчет = value;
                // *** Start programmer edit section *** (Клиент_.БанкСчет Set end)

                // *** End programmer edit section *** (Клиент_.БанкСчет Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Клиент_.ФИО CustomAttributes)

        // *** End programmer edit section *** (Клиент_.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Клиент_.ФИО Get start)

                // *** End programmer edit section *** (Клиент_.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Клиент_.ФИО Get end)

                // *** End programmer edit section *** (Клиент_.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент_.ФИО Set start)

                // *** End programmer edit section *** (Клиент_.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Клиент_.ФИО Set end)

                // *** End programmer edit section *** (Клиент_.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "Клиент_E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Клиент_E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Клиент_E", typeof(IIS.Kyrsovaya.Клиент_));
                }
            }
            
            /// <summary>
            /// "Клиент_L" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Клиент_L
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Клиент_L", typeof(IIS.Kyrsovaya.Клиент_));
                }
            }
        }
    }
}
