//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kyrsovaya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Транзакция_.
    /// </summary>
    // *** Start programmer edit section *** (Транзакция_ CustomAttributes)

    // *** End programmer edit section *** (Транзакция_ CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("Транзакция_E", new string[] {
            "Номер as \'Номер\'",
            "Билеты as \'Билеты\'",
            "Клиент_.ФИО as \'ФИО\'",
            "Билеты.ПунктОтпр as \'Пункт отпр\'",
            "Билеты.ПунктНазнач as \'Пункт назначения\'",
            "Клиент_ as \'Клиент_\'"}, Hidden=new string[] {
            "Билеты.ПунктОтпр"})]
    [MasterViewDefineAttribute("Транзакция_E", "Билеты", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ПунктОтпр")]
    [MasterViewDefineAttribute("Транзакция_E", "Клиент_", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "БанкСчет")]
    [View("Транзакция_L", new string[] {
            "Номер as \'Номер\'",
            "Билеты.ПунктОтпр as \'Пункт отпр\'",
            "Клиент_.БанкСчет as \'Банк счет\'",
            "Билеты.ПунктНазнач",
            "Клиент_.ФИО"})]
    public class Транзакция_ : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private IIS.Kyrsovaya.Билеты fБилеты;
        
        private IIS.Kyrsovaya.Клиент_ fКлиент_;
        
        // *** Start programmer edit section *** (Транзакция_ CustomMembers)

        // *** End programmer edit section *** (Транзакция_ CustomMembers)

        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Транзакция_.Номер CustomAttributes)

        // *** End programmer edit section *** (Транзакция_.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (Транзакция_.Номер Get start)

                // *** End programmer edit section *** (Транзакция_.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (Транзакция_.Номер Get end)

                // *** End programmer edit section *** (Транзакция_.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Транзакция_.Номер Set start)

                // *** End programmer edit section *** (Транзакция_.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Транзакция_.Номер Set end)

                // *** End programmer edit section *** (Транзакция_.Номер Set end)
            }
        }
        
        /// <summary>
        /// Транзакция_.
        /// </summary>
        // *** Start programmer edit section *** (Транзакция_.Билеты CustomAttributes)

        // *** End programmer edit section *** (Транзакция_.Билеты CustomAttributes)
        [PropertyStorage(new string[] {
                "Билеты"})]
        [NotNull()]
        public virtual IIS.Kyrsovaya.Билеты Билеты
        {
            get
            {
                // *** Start programmer edit section *** (Транзакция_.Билеты Get start)

                // *** End programmer edit section *** (Транзакция_.Билеты Get start)
                IIS.Kyrsovaya.Билеты result = this.fБилеты;
                // *** Start programmer edit section *** (Транзакция_.Билеты Get end)

                // *** End programmer edit section *** (Транзакция_.Билеты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Транзакция_.Билеты Set start)

                // *** End programmer edit section *** (Транзакция_.Билеты Set start)
                this.fБилеты = value;
                // *** Start programmer edit section *** (Транзакция_.Билеты Set end)

                // *** End programmer edit section *** (Транзакция_.Билеты Set end)
            }
        }
        
        /// <summary>
        /// Транзакция_.
        /// </summary>
        // *** Start programmer edit section *** (Транзакция_.Клиент_ CustomAttributes)

        // *** End programmer edit section *** (Транзакция_.Клиент_ CustomAttributes)
        [PropertyStorage(new string[] {
                "Клиент_"})]
        [NotNull()]
        public virtual IIS.Kyrsovaya.Клиент_ Клиент_
        {
            get
            {
                // *** Start programmer edit section *** (Транзакция_.Клиент_ Get start)

                // *** End programmer edit section *** (Транзакция_.Клиент_ Get start)
                IIS.Kyrsovaya.Клиент_ result = this.fКлиент_;
                // *** Start programmer edit section *** (Транзакция_.Клиент_ Get end)

                // *** End programmer edit section *** (Транзакция_.Клиент_ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Транзакция_.Клиент_ Set start)

                // *** End programmer edit section *** (Транзакция_.Клиент_ Set start)
                this.fКлиент_ = value;
                // *** Start programmer edit section *** (Транзакция_.Клиент_ Set end)

                // *** End programmer edit section *** (Транзакция_.Клиент_ Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "Транзакция_E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Транзакция_E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Транзакция_E", typeof(IIS.Kyrsovaya.Транзакция_));
                }
            }
            
            /// <summary>
            /// "Транзакция_L" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Транзакция_L
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Транзакция_L", typeof(IIS.Kyrsovaya.Транзакция_));
                }
            }
        }
    }
}
